// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVA2N8haGDWrGFH3Iy9MssIgZsQ29nVWI',
    appId: '1:647220625771:web:4410d6a855fa323a9d4c2e',
    messagingSenderId: '647220625771',
    projectId: 'arab-conversation',
    authDomain: 'arab-conversation.firebaseapp.com',
    storageBucket: 'arab-conversation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFofy5pGo0Ij60oxuHIUkJmm3f3k37ThA',
    appId: '1:647220625771:android:8ec29165cb79bbf59d4c2e',
    messagingSenderId: '647220625771',
    projectId: 'arab-conversation',
    storageBucket: 'arab-conversation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkj-83hzb46XKhoh46tO2pZZ9nh7__MGc',
    appId: '1:647220625771:ios:e7266b375e912ad19d4c2e',
    messagingSenderId: '647220625771',
    projectId: 'arab-conversation',
    storageBucket: 'arab-conversation.appspot.com',
    androidClientId: '647220625771-k647jc6lr540mt2nalqkv63sjajn41v0.apps.googleusercontent.com',
    iosClientId: '647220625771-t8bo7o4sjd27q7k5ocidjv5rmg4nvgpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.arabConversation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkj-83hzb46XKhoh46tO2pZZ9nh7__MGc',
    appId: '1:647220625771:ios:e7266b375e912ad19d4c2e',
    messagingSenderId: '647220625771',
    projectId: 'arab-conversation',
    storageBucket: 'arab-conversation.appspot.com',
    androidClientId: '647220625771-k647jc6lr540mt2nalqkv63sjajn41v0.apps.googleusercontent.com',
    iosClientId: '647220625771-t8bo7o4sjd27q7k5ocidjv5rmg4nvgpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.arabConversation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVA2N8haGDWrGFH3Iy9MssIgZsQ29nVWI',
    appId: '1:647220625771:web:eca11ca1ae6fd9659d4c2e',
    messagingSenderId: '647220625771',
    projectId: 'arab-conversation',
    authDomain: 'arab-conversation.firebaseapp.com',
    storageBucket: 'arab-conversation.appspot.com',
  );
}
